version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - "/var/mongo:/data/db"

  paicoop:
    build: ./
    container_name: paicoop
    restart: always
    depends_on:
      - mongo
    ports:
      - "80:80"
